filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /home/mehreenkabir/cowrie/var/log/cowrie/cowrie.json
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      source: cowrie
    fields_under_root: true

output.http:
  enabled: true
  url: "http://localhost:8088"
  ssl.verification_mode: none
  headers:
    Authorization: "Splunk d39b9668-acbe-4e07-b52d-58c608e9f127"

logging:
  level: info
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat.log
    keepfiles: 5
    permissions: 0644
